services:
  hospital-db:
    image: postgres:15-alpine
    container_name: hospital_postgres_prod
    environment:
      POSTGRES_DB: hospital_db_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - hospital_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  hospital_data_prod:
    driver: local